### ISSUE TITLE
adding a getting started guide

### ISSUE THREAD

**Issue by gicque** [Litipk/Jupyter-PHP-Installer#1]
Hi @castarco, Can you add a guide to install into jupyter ?

Thank you.

**Comment by castarco** [comment]
Hello @gicque , the installer isn't finished yet u_u , I hadn't been able to find more time these past weeks. I think I'll finish it in less than a couple of weeks (including documentation :) ). 

Thank you for your interest.

**Comment by gicque** [comment]
Thank you @castarco, I hope i can help you when it'll become clearer to me :)

**Comment by castarco** [comment]
@gicque , I hope the current documentation will solve your problem ;) .

**Comment by gicque** [comment]
Thank you @castarco :)
