### ISSUE TITLE
Error in Windows 10

### ISSUE THREAD

**Issue by periscuelo** [Litipk/Jupyter-PHP-Installer#11]
First thank you very much for the kernel and congratulations.

Windows 10
Apache + PHP 7.0.11
Python 3.5.2 + pip + jupyter 4.2.0 for windows

ERROR: Error while trying to download Jupyter-PHP dependencies with Composer.

What must I do to proceed with the installation?

Thanks again.

**Comment by castarco** [comment]
Hello @periscuelo . Have you installed Composer in your system?
If yes, where have you placed the composer binary?

Thank you for your report!

**Comment by periscuelo** [comment]
I just made the default install with setup.exe. Where are must be placed the binary? 
I made two tries. One with setup.exe and other manual and persists the error.
I tryed install composer manual too in root folder where php was installed, but still doesn't work. 

Thanks for response.

**Comment by castarco** [comment]
Hi @periscuelo , we recently improved Windows support, may you try if this works for you?

Thanks! (and excuse me for being too slow)

**Comment by castarco** [comment]
@bstoney I have a doubt about the behavior of the installer on Windows (I don't have any PC with Windows right now).

On the abstract `Installer` class ( https://github.com/Litipk/Jupyter-PHP-Installer/blob/master/src/Installer/Installer.php#L105 ), the verbose composer command is prefixed with the `PATH` environment variable. This is needed to run on Linux, but I'm not sure that this will work on Windows.

Can you run the installer in verbose mode to see if this works? Thank you in advance!

**Comment by ibrahim-drc** [comment]
I'm sorry for the late reply.
I installed a latest version of the composer, zeromq all for windows 10 x64
Version of PHP 7.1.1 and Lib zeromq 1.1.3 for windows 10 x64 too.
I run im prompt `php ./jupyter-php-installer.phar install` and everything is ok.

Now its running. Thank you very much. Congratulations =)
