### ISSUE TITLE
PHP option not showing up in jupyter after kernel install

### ISSUE THREAD

**Issue by SebasScript** [Litipk/Jupyter-PHP-Installer#17]
Hi I just installed the PHP kernel on mac osx and got 
"The Jupyter-PHP kernel has been successfully installed" 
But after starting jupyter notebook, there is no php option showing up when trying to create a new notebook. There are no additional steps in the installation guide, so I am not sure what the problem is?

This is the install log:

You are running PHP-CLI with xdebug enabled. This will have a major impact on the kernel's performance.

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 28 installs, 0 updates, 0 removals
  - Installing react/event-loop (v0.4.3): Downloading (100%)
  - Installing evenement/evenement (v2.1.0): Downloading (100%)
  - Installing react/zmq (v0.3.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.10): Downloading (100%)
  - Installing ramsey/uuid (3.7.0): Downloading (100%)
  - Installing jakub-onderka/php-console-color (0.1): Downloading (100%)
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Downloading (100%)
  - Installing dnoegel/php-xdg-base-dir (0.1): Downloading (100%)
  - Installing nikic/php-parser (v3.1.1): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.5.0): Downloading (100%)
  - Installing symfony/var-dumper (v3.3.8): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing symfony/debug (v3.3.8): Downloading (100%)
  - Installing symfony/console (v3.3.8): Downloading (100%)
  - Installing psy/psysh (v0.8.11): Downloading (100%)
  - Installing monolog/monolog (1.23.0): Downloading (100%)
  - Installing symfony/process (v3.3.8): Downloading (100%)
  - Installing symfony/finder (v3.3.8): Downloading (100%)
  - Installing symfony/filesystem (v3.3.8): Downloading (100%)
  - Installing seld/phar-utils (1.0.1): Downloading (100%)
  - Installing seld/jsonlint (1.6.1): Downloading (100%)
  - Installing seld/cli-prompt (1.0.3): Downloading (100%)
  - Installing justinrainbow/json-schema (5.2.1): Downloading (100%)
  - Installing composer/spdx-licenses (1.1.6): Downloading (100%)
  - Installing composer/semver (1.4.2): Downloading (100%)
  - Installing composer/ca-bundle (1.0.7): Downloading (100%)
  - Installing composer/composer (1.5.1): Downloading (100%)
  - Installing litipk/jupyter-php (0.2.0): Downloading (100%)
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/console suggests installing symfony/event-dispatcher ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Writing lock file
Generating optimized autoload files

The Jupyter-PHP kernel has been successfully installed.

**Comment by SebCorbin** [comment]
Are you on Mac OSX ?

**Comment by SebasScript** [comment]
Yes, I am on Mac OSX: Sierra, 10.12.6

**Comment by SebCorbin** [comment]
I had the same problem and created a pull request, for the time being, you can execute 
`mv ~/.local/share/jupyter/kernels/jupyter-php ~/Library/Jupyter/kernels/`

**Comment by castarco** [comment]
I've released the 0.2.1 version with the fix provided by @SebCorbin .
